name: Publish to Github Pages

on:
  push:
    branches:
      - 'release'
  # This line alone enables the manual trigger with branch selection
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v6

      - name: Set up Flutter ⬇️
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Verify Flutter installation 👀
        run: flutter --version

      - name: Build web 🔨
        run: flutter build web --release --base-href "/sudoku/"

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
